vaadin:
  launch-browser: true

datasource:
  musakan:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Baba123*
    driver-class-name: org.postgresql.Driver
    maxPoolSize: 10
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hbm2ddl:
        method: update
      show_sql: true
      format_sql: true

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: musab.akan.1998@gmail.com
    password: czkp wzfr rlwb zdbj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  reset-password:
    base-url: http://localhost:8080/reset-password
